"""Hosts the live video footage from the Raspberry Pi to a web interface.

Provides an index page and a '/video_feed' endpoint that streams MJPEG
frames generated by `capture.get_frame()`.
"""
from flask import Flask, Response, render_template_string
import time
import capture

app = Flask(__name__)

def load_index_html():
    with open('resources/index.html', 'r') as file:
        return file.read()

@app.route('/')
def index():
        return render_template_string(load_index_html())


def gen(generator):
    for frame in generator:
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


def mjpeg_stream(generator):
        return Response(gen(generator), mimetype='multipart/x-mixed-replace; boundary=frame')


@app.route('/video_feed')
def video_feed():
        return mjpeg_stream(capture.get_frame())


def run(host='0.0.0.0', port=5000):
        app.run(host=host, port=port, threaded=True)